version: "3.3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "eruditio-mongo"
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null